# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0bf1876693a954e5c2b6846b0fbdaf80e910a46a22523d33482fb0a5111d72d960b64295b7eb939e0ccfb076cceb8861fd88a87f75aefb59126067665ab6b69

test:
  secret_key_base: 3a9d5824dbff95255ed218bb7770f917cddeb7210083866977a7febac547d3a8d4169e3efb8a698e6f5b61527a5b24e3c2c9d28ff56a369b4abdd2741b1790e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
